### ISSUE TITLE
NoClassDefFoundError: com.vaadin.flow.data.binder.HasItemsAndComponents$ItemComponent

### ISSUE THREAD

**Issue by sergiopinhon** [TatuLund/TwinColSelect#14]
Hello,

First of all thank you for this wonderfull component. I've tried to update my vaadin aplication from version 14 to the latest 23 and it seems the interface ItemComponent has moved from class HasItemsAndComponents to HasItemComponents causing the exception:

Caused by: java.lang.NoClassDefFoundError: com.vaadin.flow.data.binder.HasItemsAndComponents$ItemComponent
	at java.lang.ClassLoader.defineClassImpl(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:491) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:452) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151) ~[?:?]
	at jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:1137) ~[?:?]
	at jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:924) ~[?:?]
	at jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:832) ~[?:?]
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:790) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:1108) ~[?:?]
	at java.lang.Class.getDeclaredMethodsImpl(Native Method) ~[?:?]
	at java.lang.Class.getDeclaredMethods(Class.java:1137) ~[?:?]
	at com.vaadin.flow.internal.nodefeature.AbstractServerHandlers.collectHandlerMethods(AbstractServerHandlers.java:158) ~[flow-server-23.0.3.jar:23.0.3]
	at com.vaadin.flow.internal.nodefeature.AbstractServerHandlers.collectHandlerMethods(AbstractServerHandlers.java:123) ~[flow-server-23.0.3.jar:23.0.3]
	at com.vaadin.flow.internal.nodefeature.AbstractServerHandlers.componentSet(AbstractServerHandlers.java:84) ~[flow-server-23.0.3.jar:23.0.3]
	at com.vaadin.flow.internal.nodefeature.ComponentMapping.setComponent(ComponentMapping.java:65) ~[flow-server-23.0.3.jar:23.0.3]
	at com.vaadin.flow.dom.ElementStateProvider.setComponent(ElementStateProvider.java:326) ~[flow-server-23.0.3.jar:23.0.3]
	at com.vaadin.flow.dom.ElementUtil.setComponent(ElementUtil.java:202) ~[flow-server-23.0.3.jar:23.0.3]
	at com.vaadin.flow.component.Component.setElement(Component.java:237) ~[flow-server-23.0.3.jar:23.0.3]
	at com.vaadin.flow.component.Component.setElement(Component.java:258) ~[flow-server-23.0.3.jar:23.0.3]
	at com.vaadin.flow.component.Component.<init>(Component.java:122) ~[flow-server-23.0.3.jar:23.0.3]
	at com.vaadin.flow.component.AbstractField.<init>(AbstractField.java:145) ~[flow-server-23.0.3.jar:23.0.3]
	at org.vaadin.tatu.TwinColSelect.<init>(TwinColSelect.java:224) ~[twincolselect-1.8.1.jar:1.8.1]
	at org.vaadin.tatu.TwinColSelect.<init>(TwinColSelect.java:220) ~[twincolselect-1.8.1.jar:1.8.1]

Best regards,
    Sergio

**Comment by TatuLund** [comment]
Yes, you should use TwinColSelect v2.0.0 with Vaadin 23.

**Comment by sergiopinhon** [comment]
Ok, thank you. I did not knew about the 2.0.0 version :(
